In [2]:
#https://www.kaggle.com/datasets/elmartini/gender-development-index-2019
import pandas as pd

df = pd.read_csv('GDI.csv')
df.describe()

         HDI Rank
count  189.000000
mean    94.783069
std     54.754486
min      1.000000
25%     48.000000
50%     95.000000
75%    142.000000
max    189.000000

In [3]:
df.head(20)
#Vamos precisar deletar a linha 0, pois só mostra informações sobre o ano.

,HDI Rank,Country,GDI_Value,GDI_Group,HDI_Female,HDI_Male,Lif_Expec_Female,Lif_Excep_Male,Excep_Yrs_Schooling_Female,Excep_Yrs_Schooling_Male,Mean_Yrs_Schooling_Female,Mean_Yrs_Schooling_Male,GNI_PC_Female,GNI_PC_Male
0,NaN,NaN,2019,2019,2019,2019,2019,2019,2019,2019,2019,2019,2019,2019
1,1.0,Norway,0.990,1,0.949,0.959,84.4,80.4,18.8,17.4,13.0,12.8,"58,548","74,280"
2,2.0,Ireland,0.981,1,0.943,0.961,83.9,80.7,18.8,18.6,12.9,12.4,"55,540","81,401"
3,2.0,Switzerland,0.968,2,0.934,0.965,85.6,81.9,16.2,16.4,12.7,13.6,"57,840","81,137"
4,4.0,"Hong Kong, China (SAR)",0.972,2,0.933,0.959,87.7,82.0,17.1,16.8,11.9,12.7,"45,961","82,993"
5,4.0,Iceland,0.969,2,0.933,0.963,84.5,81.5,20.2,18.0,12.6,13.0,"46,413","62,883"
6,6.0,Germany,0.972,2,0.933,0.960,83.7,78.9,16.9,17.0,13.9,14.4,"45,277","65,599"
7,7.0,Sweden,0.983,1,0.936,0.953,84.6,81.0,20.4,18.6,12.7,12.4,"47,709","61,287"
8,8.0,Australia,0.976,1,0.932,0.955,85.4,81.5,22.4,21.5,12.8,12.7,"39,287","56,954"
9,8.0,Netherlands,0.966,2,0.926,0.960,84.0,80.6,18.8,18.2,12.2,12.7,"46,815","68,685"
10,10.0,Denmark,0.983,1,0.931,0.948,82.9,78.9,19.6,18.3,12.8,12.4,"49,296","68,134"
11,11.0,Finland,0.990,1,0.932,0.942,84.7,79.1,20.2,18.6,13.0,12.6,"40,759","56,485"
12,11.0,Singapore,0.985,1,0.931,0.945,85.7,81.5,16.7,16.3,11.2,12.1,"71,387","103,421"
13,13.0,United Kingdom,0.970,2,0.916,0.944,83.0,79.6,18.0,17.0,13.2,13.2,"33,323","59,135"
14,14.0,Belgium,0.974,2,0.918,0.943,83.9,79.3,20.7,18.8,11.9,12.2,"41,948","62,427"
15,14.0,New Zealand,0.964,2,0.912,0.946,84.0,80.6,19.7,17.9,12.7,12.9,"31,233","50,693"
16,16.0,Canada,0.986,1,0.922,0.935,84.4,80.4,16.7,15.7,13.4,13.3,"39,459","57,734"
17,17.0,United States,0.994,1,0.922,0.928,81.4,76.3,16.9,15.7,13.5,13.4,"50,590","77,338"
18,18.0,Austria,0.964,2,0.903,0.937,83.9,79.2,16.4,15.8,12.2,12.9,"39,386","73,528"
19,19.0,Israel,0.973,2,0.904,0.929,84.5,81.3,16.8,15.6,13.1,13.0,"29,665","50,819"

In [6]:
df = df.drop(0)

In [7]:
df.head(20)

,HDI Rank,Country,GDI_Value,GDI_Group,HDI_Female,HDI_Male,Lif_Expec_Female,Lif_Excep_Male,Excep_Yrs_Schooling_Female,Excep_Yrs_Schooling_Male,Mean_Yrs_Schooling_Female,Mean_Yrs_Schooling_Male,GNI_PC_Female,GNI_PC_Male
1,1.0,Norway,0.990,1,0.949,0.959,84.4,80.4,18.8,17.4,13.0,12.8,"58,548","74,280"
2,2.0,Ireland,0.981,1,0.943,0.961,83.9,80.7,18.8,18.6,12.9,12.4,"55,540","81,401"
3,2.0,Switzerland,0.968,2,0.934,0.965,85.6,81.9,16.2,16.4,12.7,13.6,"57,840","81,137"
4,4.0,"Hong Kong, China (SAR)",0.972,2,0.933,0.959,87.7,82.0,17.1,16.8,11.9,12.7,"45,961","82,993"
5,4.0,Iceland,0.969,2,0.933,0.963,84.5,81.5,20.2,18.0,12.6,13.0,"46,413","62,883"
6,6.0,Germany,0.972,2,0.933,0.960,83.7,78.9,16.9,17.0,13.9,14.4,"45,277","65,599"
7,7.0,Sweden,0.983,1,0.936,0.953,84.6,81.0,20.4,18.6,12.7,12.4,"47,709","61,287"
8,8.0,Australia,0.976,1,0.932,0.955,85.4,81.5,22.4,21.5,12.8,12.7,"39,287","56,954"
9,8.0,Netherlands,0.966,2,0.926,0.960,84.0,80.6,18.8,18.2,12.2,12.7,"46,815","68,685"
10,10.0,Denmark,0.983,1,0.931,0.948,82.9,78.9,19.6,18.3,12.8,12.4,"49,296","68,134"
11,11.0,Finland,0.990,1,0.932,0.942,84.7,79.1,20.2,18.6,13.0,12.6,"40,759","56,485"
12,11.0,Singapore,0.985,1,0.931,0.945,85.7,81.5,16.7,16.3,11.2,12.1,"71,387","103,421"
13,13.0,United Kingdom,0.970,2,0.916,0.944,83.0,79.6,18.0,17.0,13.2,13.2,"33,323","59,135"
14,14.0,Belgium,0.974,2,0.918,0.943,83.9,79.3,20.7,18.8,11.9,12.2,"41,948","62,427"
15,14.0,New Zealand,0.964,2,0.912,0.946,84.0,80.6,19.7,17.9,12.7,12.9,"31,233","50,693"
16,16.0,Canada,0.986,1,0.922,0.935,84.4,80.4,16.7,15.7,13.4,13.3,"39,459","57,734"
17,17.0,United States,0.994,1,0.922,0.928,81.4,76.3,16.9,15.7,13.5,13.4,"50,590","77,338"
18,18.0,Austria,0.964,2,0.903,0.937,83.9,79.2,16.4,15.8,12.2,12.9,"39,386","73,528"
19,19.0,Israel,0.973,2,0.904,0.929,84.5,81.3,16.8,15.6,13.1,13.0,"29,665","50,819"
20,19.0,Japan,0.978,1,0.906,0.927,87.7,81.5,15.2,15.3,13.1,12.6,"30,584","55,869"