In [1]:
import pandas as pd

df = pd.read_csv('running_best_cities.csv')
df.head(50)

,Overall Rank (1=Best),City,State,Overall Score,Running Access Rank,Running Quality Rank,Foot Care Rank,Affordability Rank,Community Rank,Safety Rank,Climate Rank
0,1,San Francisco,CA,57.96,13,1,45,59,4,100,8
1,2,New York,NY,56.97,5,15,61,191,1,52,108
2,3,San Diego,CA,55.53,6,39,126,72,2,94,4
3,4,Portland,OR,55.23,1,11,43,157,12,154,15
4,5,Oakland,CA,53.47,7,5,87,138,49,83,8
5,6,Los Angeles,CA,49.34,18,6,142,121,9,126,37
6,7,Seattle,WA,48.88,21,16,62,58,11,133,18
7,8,Boston,MA,47.69,30,12,26,136,7,49,69
8,9,Salt Lake City,UT,47.16,8,19,3,66,47,176,150
9,10,San Jose,CA,47.07,23,14,174,40,54,103,8
10,11,Glendale,CA,46.78,70,2,30,53,193,35,23
11,12,Washington,DC,46.67,22,34,50,124,3,123,62
12,13,Colorado Springs,CO,46.23,2,44,134,106,19,107,121
13,14,Santa Rosa,CA,45.66,55,26,53,161,125,20,1
14,15,Richmond,VA,45.62,17,29,22,110,34,79,77
15,16,Fremont,CA,45.48,47,13,130,6,130,72,8
16,17,Pittsburgh,PA,45.30,19,74,4,141,32,73,92
17,18,Boise,ID,45.18,20,33,71,89,86,14,66
18,19,Philadelphia,PA,44.60,32,9,42,174,17,108,97
19,20,Salinas,CA,44.42,84,7,145,139,160,61,3
20,21,Las Vegas,NV,44.41,12,40,54,54,35,82,176
21,22,Irvine,CA,43.74,31,41,169,30,105,10,23
22,23,Phoenix,AZ,43.70,4,10,114,84,28,184,193
23,24,Escondido,CA,43.56,37,24,150,129,169,101,4
24,25,Chicago,IL,43.31,9,120,76,155,5,96,152
25,26,Oxnard,CA,43.23,136,8,160,70,162,30,14
26,27,Anaheim,CA,42.76,118,4,110,44,144,98,23
27,28,Pasadena,CA,42.56,94,3,58,60,100,185,23
28,29,Cincinnati,OH,42.54,10,122,11,140,40,111,143
29,30,Naperville,IL,42.28,81,66,48,22,119,1,152
30,31,San Antonio,TX,42.14,14,46,153,164,13,169,138
31,32,Virginia Beach,VA,42.05,62,31,148,57,63,16,41
32,33,Honolulu,HI,41.61,44,45,64,135,69,189,2
33,34,Scottsdale,AZ,41.47,28,21,12,27,129,63,193
34,35,Tucson,AZ,41.34,11,30,78,179,39,192,116
35,36,Atlanta,GA,41.33,33,53,19,56,10,187,81
36,37,Miami,FL,41.10,38,55,2,154,33,178,85
37,38,Minneapolis,MN,40.95,26,61,16,163,31,116,133
38,39,Austin,TX,40.80,16,64,155,85,29,160,111
39,40,Buffalo,NY,40.52,24,52,35,188,67,92,75
40,41,Albuquerque,NM,40.08,3,72,79,148,59,198,124
41,42,Anchorage,AK,40.00,15,125,143,113,30,155,58
42,43,Long Beach,CA,39.81,97,37,116,76,27,144,22
43,44,Raleigh,NC,39.55,35,70,137,114,48,54,82
44,45,Rochester,NY,39.54,46,73,7,187,46,156,67
45,46,Chula Vista,CA,39.53,113,90,175,21,185,37,4
46,47,El Paso,TX,39.51,29,60,167,95,82,32,130
47,48,Fullerton,CA,39.48,114,35,124,17,193,44,23
48,49,Santa Clarita,CA,39.43,144,49,200,31,138,4,23
49,50,Orange,CA,39.38,149,25,14,16,162,68,23

In [16]:
df.tail(20)

,Overall Rank (1=Best),City,State,Overall Score,Running Access Rank,Running Quality Rank,Foot Care Rank,Affordability Rank,Community Rank,Safety Rank,Climate Rank
180,181,McAllen,TX,27.19,179,197,144,51,147,50,101
181,182,Thornton,CO,27.10,109,176,190,168,156,93,187
182,183,Pembroke Pines,FL,27.03,184,199,119,34,193,23,85
183,184,North Las Vegas,NV,26.83,121,191,198,10,193,19,176
184,185,Cape Coral,FL,26.80,196,195,181,62,156,7,137
185,186,Detroit,MI,26.79,111,159,129,198,80,193,140
186,187,Grand Prairie,TX,26.66,167,180,199,14,165,28,161
187,188,Mesquite,TX,26.50,173,168,183,13,177,90,161
188,189,Baton Rouge,LA,26.48,123,172,39,176,94,196,183
189,190,Clarksville,TN,26.10,190,177,185,160,152,89,120
190,191,Amarillo,TX,26.00,181,185,139,131,153,110,144
191,192,West Valley City,UT,25.54,171,190,186,8,193,59,150
192,193,Ontario,CA,25.30,185,194,108,12,168,127,51
193,194,Montgomery,AL,24.65,191,193,91,94,123,143,148
194,195,Kansas City,KS,24.39,178,187,149,169,143,170,157
195,196,Pasadena,TX,24.27,162,188,172,18,193,81,191
196,197,Surprise,AZ,22.71,199,200,173,24,144,18,200
197,198,Killeen,TX,22.16,200,196,197,150,156,124,105
198,199,Jackson,MS,21.80,186,192,29,199,131,188,180
199,200,Macon,GA,21.17,197,198,81,185,107,200,102

In [2]:
resultado = list(df['State'] == 'NC')
display(df.loc[resultado])

,Overall Rank (1=Best),City,State,Overall Score,Running Access Rank,Running Quality Rank,Foot Care Rank,Affordability Rank,Community Rank,Safety Rank,Climate Rank
43,44,Raleigh,NC,39.55,35,70,137,114,48,54,82
60,61,Durham,NC,38.42,41,116,72,87,43,75,70
71,72,Charlotte,NC,37.37,72,123,132,92,8,117,83
114,115,Greensboro,NC,33.56,90,86,131,158,73,171,72
159,160,Fayetteville,NC,30.10,192,137,118,171,97,67,70
163,164,Winston-Salem,NC,29.83,161,166,73,109,78,151,78

In [2]:
resultado = list(df['State'] == 'VA')
display(df.loc[resultado])

,Overall Rank (1=Best),City,State,Overall Score,Running Access Rank,Running Quality Rank,Foot Care Rank,Affordability Rank,Community Rank,Safety Rank,Climate Rank
14,15,Richmond,VA,45.62,17,29,22,110,34,79,77
31,32,Virginia Beach,VA,42.05,62,31,148,57,63,16,41
54,55,Alexandria,VA,39.00,59,43,51,142,96,74,62
120,121,Newport News,VA,33.37,172,56,109,167,122,129,41
128,129,Chesapeake,VA,32.91,125,170,176,71,116,38,41
139,140,Norfolk,VA,32.37,129,100,163,177,127,152,41
160,161,Hampton,VA,30.06,193,184,111,93,165,45,41

In [14]:
df.sort_values(by = 'Running Quality Rank').head(20)

,Overall Rank (1=Best),City,State,Overall Score,Running Access Rank,Running Quality Rank,Foot Care Rank,Affordability Rank,Community Rank,Safety Rank,Climate Rank
0,1,San Francisco,CA,57.96,13,1,45,59,4,100,8
10,11,Glendale,CA,46.78,70,2,30,53,193,35,23
27,28,Pasadena,CA,42.56,94,3,58,60,100,185,23
26,27,Anaheim,CA,42.76,118,4,110,44,144,98,23
4,5,Oakland,CA,53.47,7,5,87,138,49,83,8
5,6,Los Angeles,CA,49.34,18,6,142,121,9,126,37
19,20,Salinas,CA,44.42,84,7,145,139,160,61,3
25,26,Oxnard,CA,43.23,136,8,160,70,162,30,14
18,19,Philadelphia,PA,44.60,32,9,42,174,17,108,97
22,23,Phoenix,AZ,43.70,4,10,114,84,28,184,193
3,4,Portland,OR,55.23,1,11,43,157,12,154,15
7,8,Boston,MA,47.69,30,12,26,136,7,49,69
15,16,Fremont,CA,45.48,47,13,130,6,130,72,8
9,10,San Jose,CA,47.07,23,14,174,40,54,103,8
1,2,New York,NY,56.97,5,15,61,191,1,52,108
6,7,Seattle,WA,48.88,21,16,62,58,11,133,18
95,96,Miramar,FL,35.69,183,17,184,4,172,9,85
78,79,Waco,TX,37.07,154,18,98,79,115,102,119
8,9,Salt Lake City,UT,47.16,8,19,3,66,47,176,150
50,51,Jersey City,NJ,39.25,96,20,101,37,106,40,125

In [6]:
df.sort_values(by = 'Climate Rank').head(60)

,Overall Rank (1=Best),City,State,Overall Score,Running Access Rank,Running Quality Rank,Foot Care Rank,Affordability Rank,Community Rank,Safety Rank,Climate Rank
13,14,Santa Rosa,CA,45.66,55,26,53,161,125,20,1
32,33,Honolulu,HI,41.61,44,45,64,135,69,189,2
19,20,Salinas,CA,44.42,84,7,145,139,160,61,3
45,46,Chula Vista,CA,39.53,113,90,175,21,185,37,4
2,3,San Diego,CA,55.53,6,39,126,72,2,94,4
23,24,Escondido,CA,43.56,37,24,150,129,169,101,4
82,83,Oceanside,CA,36.53,135,141,168,39,151,70,4
15,16,Fremont,CA,45.48,47,13,130,6,130,72,8
67,68,Hayward,CA,38.01,93,42,189,74,193,161,8
0,1,San Francisco,CA,57.96,13,1,45,59,4,100,8
9,10,San Jose,CA,47.07,23,14,174,40,54,103,8
59,60,Sunnyvale,CA,38.62,145,82,196,7,167,33,8
4,5,Oakland,CA,53.47,7,5,87,138,49,83,8
25,26,Oxnard,CA,43.23,136,8,160,70,162,30,14
108,109,Vancouver,WA,34.23,87,179,97,100,99,109,15
3,4,Portland,OR,55.23,1,11,43,157,12,154,15
125,126,Salem,OR,33.07,120,164,95,111,93,150,17
56,57,Bellevue,WA,38.92,45,129,36,88,174,57,18
6,7,Seattle,WA,48.88,21,16,62,58,11,133,18
87,88,Tacoma,WA,36.26,89,142,33,98,98,120,18
73,74,Charleston,SC,37.21,123,103,17,46,68,157,21
42,43,Long Beach,CA,39.81,97,37,116,76,27,144,22
126,127,Santa Ana,CA,33.03,139,106,151,43,180,137,23
63,64,Huntington Beach,CA,38.07,91,63,152,19,137,87,23
127,128,Lancaster,CA,33.02,198,62,166,55,162,118,23
167,168,Garden Grove,CA,29.53,187,181,171,32,193,97,23
47,48,Fullerton,CA,39.48,114,35,124,17,193,44,23
10,11,Glendale,CA,46.78,70,2,30,53,193,35,23
26,27,Anaheim,CA,42.76,118,4,110,44,144,98,23
48,49,Santa Clarita,CA,39.43,144,49,200,31,138,4,23
21,22,Irvine,CA,43.74,31,41,169,30,105,10,23
49,50,Orange,CA,39.38,149,25,14,16,162,68,23
106,107,Palmdale,CA,34.26,166,32,192,42,185,145,23
96,97,Pomona,CA,35.65,163,77,68,49,180,95,23
66,67,Torrance,CA,38.02,134,124,9,29,185,51,23
27,28,Pasadena,CA,42.56,94,3,58,60,100,185,23
5,6,Los Angeles,CA,49.34,18,6,142,121,9,126,37
156,157,Stockton,CA,30.27,146,178,161,82,161,122,38
169,170,Lubbock,TX,29.05,164,182,126,38,114,163,39
143,144,Modesto,CA,31.76,133,149,94,75,128,159,40
31,32,Virginia Beach,VA,42.05,62,31,148,57,63,16,41
139,140,Norfolk,VA,32.37,129,100,163,177,127,152,41
128,129,Chesapeake,VA,32.91,125,170,176,71,116,38,41
160,161,Hampton,VA,30.06,193,184,111,93,165,45,41
120,121,Newport News,VA,33.37,172,56,109,167,122,129,41
53,54,Eugene,OR,39.04,49,57,80,122,72,105,46
91,92,Roseville,CA,36.17,88,154,32,73,172,34,47
98,99,Sacramento,CA,35.26,50,151,56,147,42,166,48
151,152,Elk Grove,CA,31.00,95,183,195,2,177,11,48
70,71,Spokane,WA,37.46,40,102,52,117,76,158,50
132,133,Riverside,CA,32.65,79,147,99,83,153,148,51
74,75,Corona,CA,37.21,76,48,178,52,185,66,51
129,130,Rancho Cucamonga,CA,32.86,170,119,177,20,176,53,51
146,147,Fontana,CA,31.52,174,162,162,63,185,26,51
192,193,Ontario,CA,25.30,185,194,108,12,168,127,51
141,142,Moreno Valley,CA,32.04,175,68,194,3,142,78,51
173,174,San Bernardino,CA,28.50,160,111,193,132,177,194,51
41,42,Anchorage,AK,40.00,15,125,143,113,30,155,58
168,169,Bakersfield,CA,29.42,148,169,141,90,92,167,59
157,158,Port St. Lucie,FL,30.20,194,186,164,101,159,2,60

In [19]:
df.sort_values(by = 'Safety Rank').head(40)

,Overall Rank (1=Best),City,State,Overall Score,Running Access Rank,Running Quality Rank,Foot Care Rank,Affordability Rank,Community Rank,Safety Rank,Climate Rank
29,30,Naperville,IL,42.28,81,66,48,22,119,1,152
157,158,Port St. Lucie,FL,30.20,194,186,164,101,159,2,60
57,58,McKinney,TX,38.81,165,22,154,23,125,3,161
48,49,Santa Clarita,CA,39.43,144,49,200,31,138,4,23
107,108,Frisco,TX,34.24,138,174,59,1,113,5,161
93,94,Yonkers,NY,35.86,107,110,84,115,185,6,125
184,185,Cape Coral,FL,26.80,196,195,181,62,156,7,137
131,132,Aurora,IL,32.78,132,161,146,69,133,8,152
95,96,Miramar,FL,35.69,183,17,184,4,172,9,85
21,22,Irvine,CA,43.74,31,41,169,30,105,10,23
151,152,Elk Grove,CA,31.00,95,183,195,2,177,11,48
117,118,Carrollton,TX,33.50,156,112,140,9,81,12,161
144,145,Joliet,IL,31.61,108,160,96,11,153,13,152
17,18,Boise,ID,45.18,20,33,71,89,86,14,66
52,53,Plano,TX,39.11,75,38,88,26,121,15,161
31,32,Virginia Beach,VA,42.05,62,31,148,57,63,16,41
118,119,Olathe,KS,33.49,106,87,180,5,131,17,157
196,197,Surprise,AZ,22.71,199,200,173,24,144,18,200
183,184,North Las Vegas,NV,26.83,121,191,198,10,193,19,176
13,14,Santa Rosa,CA,45.66,55,26,53,161,125,20,1
90,91,Henderson,NV,36.19,65,92,123,45,140,21,176
147,148,Laredo,TX,31.38,176,126,191,96,169,22,80
182,183,Pembroke Pines,FL,27.03,184,199,119,34,193,23,85
124,125,Bridgeport,CT,33.16,151,143,70,137,180,24,65
86,87,Overland Park,KS,36.32,126,69,44,80,124,25,157
146,147,Fontana,CA,31.52,174,162,162,63,185,26,51
109,110,Warren,MI,34.19,180,133,8,35,185,27,140
186,187,Grand Prairie,TX,26.66,167,180,199,14,165,28,161
112,113,Murfreesboro,TN,33.89,195,54,90,28,169,29,131
25,26,Oxnard,CA,43.23,136,8,160,70,162,30,14
100,101,Worcester,MA,34.58,105,146,60,86,58,31,135
46,47,El Paso,TX,39.51,29,60,167,95,82,32,130
59,60,Sunnyvale,CA,38.62,145,82,196,7,167,33,8
91,92,Roseville,CA,36.17,88,154,32,73,172,34,47
10,11,Glendale,CA,46.78,70,2,30,53,193,35,23
150,151,Garland,TX,31.09,157,132,187,36,180,36,161
45,46,Chula Vista,CA,39.53,113,90,175,21,185,37,4
128,129,Chesapeake,VA,32.91,125,170,176,71,116,38,41
155,156,Peoria,AZ,30.32,169,105,120,68,147,39,193
50,51,Jersey City,NJ,39.25,96,20,101,37,106,40,125

In [20]:
resultado = list(df['State'] == 'FL')
display(df.loc[resultado])

,Overall Rank (1=Best),City,State,Overall Score,Running Access Rank,Running Quality Rank,Foot Care Rank,Affordability Rank,Community Rank,Safety Rank,Climate Rank
36,37,Miami,FL,41.10,38,55,2,154,33,178,85
89,90,St. Petersburg,FL,36.22,74,76,85,108,36,165,73
92,93,Tampa,FL,36.06,86,99,23,64,44,175,73
95,96,Miramar,FL,35.69,183,17,184,4,172,9,85
102,103,Orlando,FL,34.48,58,139,20,116,26,190,117
111,112,Jacksonville,FL,33.96,73,134,112,119,21,153,114
113,114,Tallahassee,FL,33.66,67,115,115,156,61,91,182
115,116,Fort Lauderdale,FL,33.56,100,59,27,50,95,197,85
148,149,Hialeah,FL,31.36,159,165,41,159,147,48,85
153,154,Hollywood,FL,30.66,128,171,46,134,103,130,85
157,158,Port St. Lucie,FL,30.20,194,186,164,101,159,2,60
182,183,Pembroke Pines,FL,27.03,184,199,119,34,193,23,85
184,185,Cape Coral,FL,26.80,196,195,181,62,156,7,137

In [9]:
estados = df.groupby('State')['City'].count()
display(estados)

State
AK     1
AL     4
AR     1
AZ     9
CA    43
CO     6
CT     1
DC     1
FL    13
GA     5
HI     1
IA     1
ID     1
IL     5
IN     2
KS     4
KY     2
LA     3
MA     3
MD     1
MI     3
MN     2
MO     3
MS     1
NC     6
NE     2
NJ     3
NM     1
NV     4
NY     5
OH     6
OK     2
OR     3
PA     2
RI     1
SC     1
SD     1
TN     6
TX    25
UT     2
VA     7
WA     5
WI     2
Name: City, dtype: int64

In [10]:
resultado = list(df['State'] == 'TX')
display(df.loc[resultado])

,Overall Rank (1=Best),City,State,Overall Score,Running Access Rank,Running Quality Rank,Foot Care Rank,Affordability Rank,Community Rank,Safety Rank,Climate Rank
30,31,San Antonio,TX,42.14,14,46,153,164,13,169,138
38,39,Austin,TX,40.80,16,64,155,85,29,160,111
46,47,El Paso,TX,39.51,29,60,167,95,82,32,130
52,53,Plano,TX,39.11,75,38,88,26,121,15,161
57,58,McKinney,TX,38.81,165,22,154,23,125,3,161
62,63,Houston,TX,38.20,27,84,133,145,6,172,191
75,76,Dallas,TX,37.18,43,81,100,143,16,173,161
78,79,Waco,TX,37.07,154,18,98,79,115,102,119
99,100,Fort Worth,TX,35.14,101,80,147,67,22,140,161
107,108,Frisco,TX,34.24,138,174,59,1,113,5,161
116,117,Arlington,TX,33.53,131,65,125,81,141,88,161
117,118,Carrollton,TX,33.50,156,112,140,9,81,12,161
135,136,Irving,TX,32.53,147,67,158,61,144,112,161
147,148,Laredo,TX,31.38,176,126,191,96,169,22,80
149,150,Corpus Christi,TX,31.13,130,144,136,122,88,134,68
150,151,Garland,TX,31.09,157,132,187,36,180,36,161
164,165,Denton,TX,29.82,158,167,104,65,133,65,161
169,170,Lubbock,TX,29.05,164,182,126,38,114,163,39
176,177,Brownsville,TX,28.17,189,157,182,151,180,60,84
180,181,McAllen,TX,27.19,179,197,144,51,147,50,101
186,187,Grand Prairie,TX,26.66,167,180,199,14,165,28,161
187,188,Mesquite,TX,26.50,173,168,183,13,177,90,161
190,191,Amarillo,TX,26.00,181,185,139,131,153,110,144
195,196,Pasadena,TX,24.27,162,188,172,18,193,81,191
197,198,Killeen,TX,22.16,200,196,197,150,156,124,105

In [12]:
estados = df['State'].value_counts()
display(estados)

CA    43
TX    25
FL    13
AZ     9
VA     7
OH     6
TN     6
NC     6
CO     6
WA     5
NY     5
GA     5
IL     5
KS     4
AL     4
NV     4
MO     3
LA     3
MI     3
OR     3
NJ     3
MA     3
IN     2
OK     2
NE     2
WI     2
KY     2
UT     2
MN     2
PA     2
AR     1
SD     1
CT     1
AK     1
MD     1
SC     1
IA     1
RI     1
NM     1
HI     1
ID     1
DC     1
MS     1
Name: State, dtype: int64

In [11]:
resultado = list(df['State'] == 'VA')
display(df.loc[resultado])

,Overall Rank (1=Best),City,State,Overall Score,Running Access Rank,Running Quality Rank,Foot Care Rank,Affordability Rank,Community Rank,Safety Rank,Climate Rank
14,15,Richmond,VA,45.62,17,29,22,110,34,79,77
31,32,Virginia Beach,VA,42.05,62,31,148,57,63,16,41
54,55,Alexandria,VA,39.00,59,43,51,142,96,74,62
120,121,Newport News,VA,33.37,172,56,109,167,122,129,41
128,129,Chesapeake,VA,32.91,125,170,176,71,116,38,41
139,140,Norfolk,VA,32.37,129,100,163,177,127,152,41
160,161,Hampton,VA,30.06,193,184,111,93,165,45,41

In [3]:
resultado = list(df['State'] == 'OR')
display(df.loc[resultado])

,Overall Rank (1=Best),City,State,Overall Score,Running Access Rank,Running Quality Rank,Foot Care Rank,Affordability Rank,Community Rank,Safety Rank,Climate Rank
3,4,Portland,OR,55.23,1,11,43,157,12,154,15
53,54,Eugene,OR,39.04,49,57,80,122,72,105,46
125,126,Salem,OR,33.07,120,164,95,111,93,150,17

In [3]:
resultado = list(df['State'] == 'CA')
display(df.loc[resultado])

,Overall Rank (1=Best),City,State,Overall Score,Running Access Rank,Running Quality Rank,Foot Care Rank,Affordability Rank,Community Rank,Safety Rank,Climate Rank
0,1,San Francisco,CA,57.96,13,1,45,59,4,100,8
2,3,San Diego,CA,55.53,6,39,126,72,2,94,4
4,5,Oakland,CA,53.47,7,5,87,138,49,83,8
5,6,Los Angeles,CA,49.34,18,6,142,121,9,126,37
9,10,San Jose,CA,47.07,23,14,174,40,54,103,8
10,11,Glendale,CA,46.78,70,2,30,53,193,35,23
13,14,Santa Rosa,CA,45.66,55,26,53,161,125,20,1
15,16,Fremont,CA,45.48,47,13,130,6,130,72,8
19,20,Salinas,CA,44.42,84,7,145,139,160,61,3
21,22,Irvine,CA,43.74,31,41,169,30,105,10,23
23,24,Escondido,CA,43.56,37,24,150,129,169,101,4
25,26,Oxnard,CA,43.23,136,8,160,70,162,30,14
26,27,Anaheim,CA,42.76,118,4,110,44,144,98,23
27,28,Pasadena,CA,42.56,94,3,58,60,100,185,23
42,43,Long Beach,CA,39.81,97,37,116,76,27,144,22
45,46,Chula Vista,CA,39.53,113,90,175,21,185,37,4
47,48,Fullerton,CA,39.48,114,35,124,17,193,44,23
48,49,Santa Clarita,CA,39.43,144,49,200,31,138,4,23
49,50,Orange,CA,39.38,149,25,14,16,162,68,23
59,60,Sunnyvale,CA,38.62,145,82,196,7,167,33,8
63,64,Huntington Beach,CA,38.07,91,63,152,19,137,87,23
66,67,Torrance,CA,38.02,134,124,9,29,185,51,23
67,68,Hayward,CA,38.01,93,42,189,74,193,161,8
74,75,Corona,CA,37.21,76,48,178,52,185,66,51
82,83,Oceanside,CA,36.53,135,141,168,39,151,70,4
91,92,Roseville,CA,36.17,88,154,32,73,172,34,47
96,97,Pomona,CA,35.65,163,77,68,49,180,95,23
98,99,Sacramento,CA,35.26,50,151,56,147,42,166,48
106,107,Palmdale,CA,34.26,166,32,192,42,185,145,23
126,127,Santa Ana,CA,33.03,139,106,151,43,180,137,23
127,128,Lancaster,CA,33.02,198,62,166,55,162,118,23
129,130,Rancho Cucamonga,CA,32.86,170,119,177,20,176,53,51
132,133,Riverside,CA,32.65,79,147,99,83,153,148,51
141,142,Moreno Valley,CA,32.04,175,68,194,3,142,78,51
143,144,Modesto,CA,31.76,133,149,94,75,128,159,40
146,147,Fontana,CA,31.52,174,162,162,63,185,26,51
151,152,Elk Grove,CA,31.00,95,183,195,2,177,11,48
156,157,Stockton,CA,30.27,146,178,161,82,161,122,38
161,162,Fresno,CA,29.99,142,131,135,91,84,177,118
167,168,Garden Grove,CA,29.53,187,181,171,32,193,97,23
168,169,Bakersfield,CA,29.42,148,169,141,90,92,167,59
173,174,San Bernardino,CA,28.50,160,111,193,132,177,194,51
192,193,Ontario,CA,25.30,185,194,108,12,168,127,51

In [12]:
resultado = list(df['State'] == 'NJ')
display(df.loc[resultado])

,Overall Rank (1=Best),City,State,Overall Score,Running Access Rank,Running Quality Rank,Foot Care Rank,Affordability Rank,Community Rank,Safety Rank,Climate Rank
50,51,Jersey City,NJ,39.25,96,20,101,37,106,40,125
145,146,Newark,NJ,31.58,117,28,165,200,175,131,129
166,167,Paterson,NJ,29.74,152,152,105,190,185,46,125

In [3]:
resultado = list(df['State'] == 'WA')
display(df.loc[resultado])

,Overall Rank (1=Best),City,State,Overall Score,Running Access Rank,Running Quality Rank,Foot Care Rank,Affordability Rank,Community Rank,Safety Rank,Climate Rank
6,7,Seattle,WA,48.88,21,16,62,58,11,133,18
56,57,Bellevue,WA,38.92,45,129,36,88,174,57,18
70,71,Spokane,WA,37.46,40,102,52,117,76,158,50
87,88,Tacoma,WA,36.26,89,142,33,98,98,120,18
108,109,Vancouver,WA,34.23,87,179,97,100,99,109,15

In [3]:
df.sort_values(by = 'Climate Rank').head(50)

,Overall Rank (1=Best),City,State,Overall Score,Running Access Rank,Running Quality Rank,Foot Care Rank,Affordability Rank,Community Rank,Safety Rank,Climate Rank
13,14,Santa Rosa,CA,45.66,55,26,53,161,125,20,1
32,33,Honolulu,HI,41.61,44,45,64,135,69,189,2
19,20,Salinas,CA,44.42,84,7,145,139,160,61,3
45,46,Chula Vista,CA,39.53,113,90,175,21,185,37,4
2,3,San Diego,CA,55.53,6,39,126,72,2,94,4
23,24,Escondido,CA,43.56,37,24,150,129,169,101,4
82,83,Oceanside,CA,36.53,135,141,168,39,151,70,4
15,16,Fremont,CA,45.48,47,13,130,6,130,72,8
67,68,Hayward,CA,38.01,93,42,189,74,193,161,8
0,1,San Francisco,CA,57.96,13,1,45,59,4,100,8
9,10,San Jose,CA,47.07,23,14,174,40,54,103,8
59,60,Sunnyvale,CA,38.62,145,82,196,7,167,33,8
4,5,Oakland,CA,53.47,7,5,87,138,49,83,8
25,26,Oxnard,CA,43.23,136,8,160,70,162,30,14
108,109,Vancouver,WA,34.23,87,179,97,100,99,109,15
3,4,Portland,OR,55.23,1,11,43,157,12,154,15
125,126,Salem,OR,33.07,120,164,95,111,93,150,17
56,57,Bellevue,WA,38.92,45,129,36,88,174,57,18
6,7,Seattle,WA,48.88,21,16,62,58,11,133,18
87,88,Tacoma,WA,36.26,89,142,33,98,98,120,18
73,74,Charleston,SC,37.21,123,103,17,46,68,157,21
42,43,Long Beach,CA,39.81,97,37,116,76,27,144,22
126,127,Santa Ana,CA,33.03,139,106,151,43,180,137,23
63,64,Huntington Beach,CA,38.07,91,63,152,19,137,87,23
127,128,Lancaster,CA,33.02,198,62,166,55,162,118,23
167,168,Garden Grove,CA,29.53,187,181,171,32,193,97,23
47,48,Fullerton,CA,39.48,114,35,124,17,193,44,23
10,11,Glendale,CA,46.78,70,2,30,53,193,35,23
26,27,Anaheim,CA,42.76,118,4,110,44,144,98,23
48,49,Santa Clarita,CA,39.43,144,49,200,31,138,4,23
21,22,Irvine,CA,43.74,31,41,169,30,105,10,23
49,50,Orange,CA,39.38,149,25,14,16,162,68,23
106,107,Palmdale,CA,34.26,166,32,192,42,185,145,23
96,97,Pomona,CA,35.65,163,77,68,49,180,95,23
66,67,Torrance,CA,38.02,134,124,9,29,185,51,23
27,28,Pasadena,CA,42.56,94,3,58,60,100,185,23
5,6,Los Angeles,CA,49.34,18,6,142,121,9,126,37
156,157,Stockton,CA,30.27,146,178,161,82,161,122,38
169,170,Lubbock,TX,29.05,164,182,126,38,114,163,39
143,144,Modesto,CA,31.76,133,149,94,75,128,159,40
31,32,Virginia Beach,VA,42.05,62,31,148,57,63,16,41
139,140,Norfolk,VA,32.37,129,100,163,177,127,152,41
128,129,Chesapeake,VA,32.91,125,170,176,71,116,38,41
160,161,Hampton,VA,30.06,193,184,111,93,165,45,41
120,121,Newport News,VA,33.37,172,56,109,167,122,129,41
53,54,Eugene,OR,39.04,49,57,80,122,72,105,46
91,92,Roseville,CA,36.17,88,154,32,73,172,34,47
98,99,Sacramento,CA,35.26,50,151,56,147,42,166,48
151,152,Elk Grove,CA,31.00,95,183,195,2,177,11,48
70,71,Spokane,WA,37.46,40,102,52,117,76,158,50